<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class InformeAntiguedad extends Model
{
    protected $fillable = [
        'Tipo',
        'Codigo_SN',
        'Nombre_SN',
        'Nit',
        'Grupo',
        'Cuenta',
        'CuentaVisible',
        'Tipo_Doc',
        'Documento',
        'Numero_de_referencia',
        'Numero_de_plazos',
        'Numero_plazo',
        'Fecha_de_contabilizacion',
        'Fecha_Vencimiento',
        'Fecha_de_Documento',
        'Dias',
        'LimiteCredito',
        'Importe_Original',
        'Saldo_Vencido',
        'Sin_Vencer',
        'Proyecto',
        'ProyectoNom',
        '1-15',
        '16-30',
        '0-30',
        '31-60',
        '61-90',
        '91-120',
        '121-150',
        '151-180',
        '> 180',
        '> 90',
        '> 121',
        'Territorio',
        'Telefono',
        'Fax',
        'Telefono2',
        'Celular',
        'Email',
        'NombreEmpleado',
        'Empleado',
        'Valor_Abonado',
        'Municipio',
        'DestinatarioFactura',
        'DestinatarioMercancia',
        'Responsable',
        'ValorChequesAplicados',
        'FCCurrency',
        'ImporteMS',
        'SaldoVencidoMS',
        'Valor_Abonado_MS',
        'Sin_Vencer_MS',
        '1-15_MS',
        '16-30_MS',
        '0-30_MS',
        '31-60_MS',
        '61-90_MS',
        '91-120_MS',
        '121-150_MS',
        '151-180_MS',
        '> 180_MS',
        'ImporteME',
        'SaldoVencidoME',
        'Valor_Abonado_ME',
        'Sin_Vencer_ME',
        '1-15_ME',
        '16-30_ME',
        '0-30_ME',
        '31-60_ME',
        '61-90_ME',
        '91-120_ME',
        '121-150_ME',
        '151-180_ME',
        '> 180_ME',
        'PYMNTGROUP',
        'DocumentoBase',
        'MonExtr',
        'Referencia1',
        'DocEntry',
        'TransType',
        'CondicionPagoDocumento',
    ];
}
